### ISSUE TITLE
thrift_hive_metastore_client.ttypes.MetaException: MetaException(message='java.lang.NullPointerException')

### ISSUE THREAD

**Issue by lockfu** [quintoandar/hive-metastore-client#59]
---
name: call create_table raise java.lang.NullPointerException
about: Problems and issues with code or docs
title: ''
labels: bug
assignees: ''

---

**Describe the bug**

i use the python lib, and call create_table func then raise  java.lang.NullPointerException:

Traceback (most recent call last):
  File "gittb.py", line 53, in <module>
    hive_metastore_client.create_table(table)
  File "/home/ec2-user/lfyang/spark-ui/jupyter/yes/lib/python3.8/site-packages/thrift_files/libraries/thrift_hive_metastore_client/ThriftHiveMetastore.py", line 2633, in create_table
    self.recv_create_table()
  File "/home/ec2-user/lfyang/spark-ui/jupyter/yes/lib/python3.8/site-packages/thrift_files/libraries/thrift_hive_metastore_client/ThriftHiveMetastore.py", line 2659, in recv_create_table
    raise result.o3
thrift_files.libraries.thrift_hive_metastore_client.ttypes.MetaException: MetaException(message='java.lang.NullPointerException')

**To Reproduce**

_Steps to reproduce the behavior:_
1.  pip install hive-metastore-client
2.  code file createtable.py: 
     from hive_metastore_client import HiveMetastoreClient
from hive_metastore_client.builders import (
    ColumnBuilder,
    SerDeInfoBuilder,
    StorageDescriptorBuilder,
    TableBuilder,
)

HIVE_HOST = "xxx"
HIVE_PORT = 9083

columns = [
    ColumnBuilder("id", "string", "col comment").build(),
    ColumnBuilder("client_name", "string").build(),
    ColumnBuilder("amount", "string").build(),
    ColumnBuilder("year", "string").build(),
    ColumnBuilder("month", "string").build(),
    ColumnBuilder("day", "string").build(),
]

partition_keys = [
    ColumnBuilder("year", "string").build(),
    ColumnBuilder("month", "string").build(),
    ColumnBuilder("day", "string").build(),
]

serde_info = SerDeInfoBuilder(
    serialization_lib="org.apache.hadoop.hive.ql.io.orc.OrcSerde"
).build()

storage_descriptor = StorageDescriptorBuilder(
    columns=columns,
    location="s3a://mys3bucket/xx",
    input_format="org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat",
    output_format="org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat",
    serde_info=serde_info,
).build()

table = TableBuilder(
    table_name="test_tmp_table",
    db_name="default",
    owner="owner name",
    storage_descriptor=storage_descriptor,
    partition_keys=partition_keys,
).build()

with HiveMetastoreClient(HIVE_HOST, HIVE_PORT) as hive_metastore_client:
    hive_metastore_client.create_table(table)
3. python createtable.py
4. _See error_

**Screenshots**

_If applicable, add screenshots to help explain your problem._

**Expected behavior**

_A clear and concise description of what you expected to happen._

**Environment**

- **Python** Python 3.8.5:
- **Lib** version:
- **Hive Metastore** 1.2.2:
- **Other** (e.g. OS): 

**Additional info**

_Add any other context about the problem here._

**Comment by LucasMMota** [comment]
Hello, @lockfu !
Please follow the [bug report template](https://github.com/quintoandar/hive-metastore-client/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) and provide us all the info requested in the template (like the entire code snippet you used and screenshots of the errors). So we can better help you.

**Comment by kenjihiraoka** [comment]
Hi @lockfu!

Please check if the jar with the OrcSerde class is installed at your Hive Metastore implementation, and follow the instructions above to debug the error.

**Comment by lockfu** [comment]
Hi @LucasMMota , Thanks for your answer and I have corrected my issue. Looking forward to your further answers。
@kenjihiraoka , For the OrcSerde class, i'm sure the class has been installed in my Hive Metastore implementation.

Thanks!

**Comment by lockfu** [comment]
By the way, when i use create_external_table instead of create_table function,  I can create the table successfully.

**Comment by lockfu** [comment]
Hi @kenjihiraoka , @LucasMMota ,  

reconfig table as bellow:
table = TableBuilder(
    table_name="audience_segment_tmp_nnttt",
    db_name="test_dbs",
    owner="root",
    storage_descriptor=storage_descriptor,
    **table_type="MANAGED_TABLE",
    parameters={"EXTERNAL": "FALSE"}**
    partition_keys=partition_keys
).build()

and it work !!

so is it means that when you create table in hive, it must to point out that the table is a managed table or external table?
