### ISSUE TITLE
Program hangs after first method call

### ISSUE THREAD

**Issue by StewartThomson** [quintoandar/hive-metastore-client#69]
**Describe the bug**

When calling methods in a loop, only the first call succeeds. The next subsequent call seems to hang indefinitely. Event if you use the same table in succession. This happens with any method call, not just get_partition_keys_objects

**To Reproduce**

_Steps to reproduce the behavior:_
```
from hive_metastore_client import HiveMetastoreClient

tables = [
  "my_table",
  "my_table",
]
with HiveMetastoreClient(
    "my_url"
) as hive_client:
  for table in tables:
    print(table)
    print(hive_client.get_partition_keys_objects("default", table))
```

**Expected behavior**

Each call should succeed in a timely manner 

**Environment**

- **Python** version: 3.7
- **Lib** version: 1.0.9
- **Hive Metastore** version: 2.3.8
- **Other** (e.g. OS): Ubuntu 18.04

**Comment by StewartThomson** [comment]
I believe the way to fix this is to use the client as such:

```
from hive_metastore_client import HiveMetastoreClient

tables = [
  "my_table",
  "my_table",
]

for table in tables:
  print(table)
  with HiveMetastoreClient(
      "my_url"
  ) as hive_client:
    print(hive_client.get_partition_keys_objects("default", table))
```

**Comment by felipemiquelim** [comment]
@StewartThomson Thanks for the feedback!

Actually we've run the code for multiple calls and for diff methods as you suggested. But we did not find any issues. 
Attached is an example of a very simple run that returned results (in this case both cases have similar partitions, so the results are the same).

![hive_metastore_client_usage](https://user-images.githubusercontent.com/11505309/160002495-da6c85a3-ce1a-4c96-979c-61e89b8dc693.png)


I'd double check the Hive configurations, maybe it is configured to only return one request per connection?

The way you solved the problem may work, however it is unfortunately spawning one connection per request, what can raise some issues down the road.
